server:
  port: 8080

spring:
  application:
    name: obsession

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/obsession?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: obsession
    password: obsession

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace


jwt:
  secret: "obsession-obsession-obsession-obsession-obsession-secret-key-123456789"
  access-token-expiration-millis: 1800000   # 30분
  refresh-token-expiration-millis: 1209600000 # 14일

app:
  redis:
    key-prefix: ${APP_REDIS_KEY_PREFIX:obsession:local}

payment:
  toss:
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    base-url: https://api.tosspayments.com