server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: obsession-app

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/${MYSQL_DATABASE:obsession}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:obsession}
    password: ${MYSQL_PASSWORD:obsession}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-millis: ${JWT_ACCESS_TOKEN_EXPIRE_MILLIS:3600000} # 1 hour
  refresh-token-expiration-millis: ${JWT_REFRESH_TOKEN_EXPIRE_MILLIS:604800000} # 7 days

app:
  redis:
    key-prefix: ${APP_REDIS_KEY_PREFIX:obsession:local}

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY}
    base-url: ${TOSS_BASE_URL:https://api.tosspayments.com}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true